import { createPublicClient, encodeAbiParameters, getFunctionSelector, keccak256, http, type Address, type Hex } from 'viem';
import { seal } from '../src/launchConfig/ponsLaunchManifest.js';
import { PONS_STAKING_FACTORY_V1, PONS_V2_FACTORY_V1, PONS_VAULT_LAUNCHER_V1, PONS_VAULT_REGISTRY_V1 } from '../src/launchConfig/ponsPlan.js';
import { PONS_STAKING_BEACON_V1, PONS_STAKING_IMPLEMENTATION_V1, registryStakingFactoryCalldata, PONS_PREFLIGHT_SELECTORS as S } from '../src/launchConfig/ponsPreflight.js';
const client=createPublicClient({transport:http(process.env.BINRAT_ROBINHOOD_ARCHIVE_RPC_URL ?? 'https://rpc.mainnet.chain.robinhood.com',{retryCount:0,timeout:6000})});
const base={schemaVersion:'binrat.pons-upstream-diagnostic/1',observedAt:new Date().toISOString(),classification:'READ_ONLY_DIAGNOSTIC_NOT_LAUNCH_AUTHORITY',signing:false,broadcast:false,launchAuthorized:false,workingRatStatus:'PLANNED',productionEntitlementActive:false,stakingRequired:true};
try {
  if (await client.getChainId() !== 4663) throw new Error('CHAIN_MISMATCH');
  const block=await client.getBlock({blockTag:'latest'});
  if (!block.hash || block.number === null) throw new Error('HEAD_UNAVAILABLE');
  const blockNumber=block.number;
  const authorities={ponsFactory:PONS_V2_FACTORY_V1,launcher:PONS_VAULT_LAUNCHER_V1,registry:PONS_VAULT_REGISTRY_V1,stakingFactory:PONS_STAKING_FACTORY_V1,stakingBeacon:PONS_STAKING_BEACON_V1,stakingImplementation:PONS_STAKING_IMPLEMENTATION_V1};
  const codehashes:Record<string,string>={};
  await Promise.all(Object.entries(authorities).map(async([role,address])=>{const code=await client.getCode({address,blockNumber});codehashes[role]=code && code !== '0x' ? keccak256(code) : 'UNKNOWN';}));
  const configArg=encodeAbiParameters([{type:'uint256'}],[0n]);
  const calls:[string,Address,Hex][]=[['launcherPonsFactory',PONS_VAULT_LAUNCHER_V1,S.launcherPonsFactory],['launcherRegistry',PONS_VAULT_LAUNCHER_V1,S.launcherRegistry],['registryStakingFactory',PONS_VAULT_REGISTRY_V1,registryStakingFactoryCalldata()],['registryOwner',PONS_VAULT_REGISTRY_V1,S.registryOwner],['stakingFactoryOwner',PONS_STAKING_FACTORY_V1,S.stakingFactoryOwner],['stakingFactoryBeacon',PONS_STAKING_FACTORY_V1,S.stakingFactoryBeacon],['stakingFactoryImplementation',PONS_STAKING_FACTORY_V1,S.stakingFactoryImplementation],['beaconOwner',PONS_STAKING_BEACON_V1,S.beaconOwner],['beaconImplementation',PONS_STAKING_BEACON_V1,S.beaconImplementation],['ponsOwner',PONS_V2_FACTORY_V1,S.registryOwner],['launchFee',PONS_V2_FACTORY_V1,getFunctionSelector('launchFee()')],['launchConfigCount',PONS_V2_FACTORY_V1,getFunctionSelector('launchConfigCount()')],['candidateConfig0_NOT_OWNER_FROZEN',PONS_V2_FACTORY_V1,`${getFunctionSelector('getLaunchConfig(uint256)')}${configArg.slice(2)}`],['candidatePreview0Native_NOT_OWNER_FROZEN',PONS_V2_FACTORY_V1,`${getFunctionSelector('previewLaunchEconomics(uint256,address)')}${encodeAbiParameters([{type:'uint256'},{type:'address'}],[0n,'0x0000000000000000000000000000000000000000']).slice(2)}`],...['launchForwarder','launchDeployer','launchEnabled','snipeTaxStartBps','snipeTaxSeconds'].map(name=>[name,PONS_V2_FACTORY_V1,getFunctionSelector(`${name}()`)] as [string,Address,Hex])];
  const rawCalls:Record<string,{target:Address;calldata:Hex;result:Hex|null;status:string;latencyMs:number}>={};
  await Promise.all(calls.map(async([key,to,data])=>{const start=performance.now();try {const result=await client.call({to,data,blockNumber});rawCalls[key]={target:to,calldata:data,result:result.data ?? null,status:result.data ? 'OBSERVED_NOT_BEHAVIOR_PROOF' : 'UNKNOWN',latencyMs:Math.ceil(performance.now()-start)};}catch {rawCalls[key]={target:to,calldata:data,result:null,status:'UNAVAILABLE',latencyMs:Math.ceil(performance.now()-start)};}}));
  const intervals=await Promise.all([0n,20n,40n,60n].map(offset=>client.getBlock({blockNumber:blockNumber-offset})));
  const blockIntervalsMs=intervals.slice(1).map((previous,i)=>Math.ceil(Number(intervals[i].timestamp-previous.timestamp)*1000/20));
  const canonical=(await client.getBlock({blockNumber})).hash === block.hash;
  process.stdout.write(`${JSON.stringify(await seal({...base,status:'BLOCKED_CRITICAL_BEHAVIOR_AND_OWNER_INPUTS',chainId:4663,block:{number:String(blockNumber),hash:block.hash},canonicalRecheck:canonical,codehashes,rawCalls,measurements:{blockIntervalsMs,rpcRoundTripsMs:Object.values(rawCalls).map(r=>r.latencyMs),signingWorkflowMs:null,runtimeMaxAgeMs:null,freshnessBudget:'UNRESOLVED'},independentConfirmation:'UNAVAILABLE_NOT_CONFIGURED',exactWalletCanLaunch:'UNKNOWN_OWNER_WALLET_NOT_SELECTED',assets:{pairQuoteAsset:'NATIVE_ETH_SELECTED_NOT_EXECUTED',vaultQuoteAsset:'UNKNOWN_FOR_BINRAT',feeAccountingAsset:'UNKNOWN',rewardAccountingAsset:'UNKNOWN',claimAsset:'UNKNOWN'},criticalBehavior:'UNKNOWN_UNTIL_REPRODUCIBLE_ABI_FORK_TRACE_SOURCE_BINDING',sourceRuntimeBinding:'NOT_ESTABLISHED'}),null,2)}\n`);
} catch {
  process.stdout.write(`${JSON.stringify(await seal({...base,status:'BLOCKED_RPC_UNAVAILABLE',chainId:4663,criticalBehavior:'UNKNOWN',freshnessBudget:'UNRESOLVED',errorCode:'RPC_OR_PINNED_STATE_UNAVAILABLE'}),null,2)}\n`);
}
