import { readFile, writeFile } from 'node:fs/promises';
import { sha256Hex } from '../src/evidence/canonical.js';
import { GATE_PHASES, REQUIRED_LAUNCH_GATE_IDS } from '../src/launchConfig/gateMatrix.js';
const root=new URL('../',import.meta.url);
const load=async(path:string)=>JSON.parse(await readFile(new URL(path,root),'utf8'));
const save=async(path:string,value:unknown)=>writeFile(new URL(path,root),`${JSON.stringify(value,null,2)}\n`);
const plan=await load('docs/BINRAT_PONS_LAUNCH_PLAN_V1.json');
plan.schemaVersion='binrat.pons-launch-plan/0.2';
plan.stakingRequired=true; plan.workingRatStatus='PLANNED'; plan.productionEntitlementActive=false;
plan.launchRail.ponsFactory.verificationStatus='LIVE_CODEHASH_PINNED_CURRENT_SOURCE_RUNTIME_MATCH_NOT_ESTABLISHED';
plan.upstreamRisk.explicitUpstreamRiskAcceptanceRequired=true;
plan.upstreamRisk.boundedAcceptance='EXACT_MANIFEST_ONLY_AFTER_INDEPENDENT_CRITICAL_BEHAVIOR_VERIFICATION';
plan.inputClassification={owner:['launchWalletAddress','tokenMetadata','minimumFeesBeforePayoutWei'],freshChain:['launchConfigId','expectedEconomics'],deferred:['workingRatMinStakeRaw'],conditional:['treasuryAddress'],postBroadcast:['tokenAddress','curveAddress','vaultAddress','transaction','block','blockHash']};
plan.authorityArtifacts={semanticManifestSchema:'binrat.pons-semantic-manifest/1',executionEnvelopeSchema:'binrat.pons-execution-envelope/1',publicFactsSchema:'binrat.pons-launch-facts/1',freshnessBudget:'UNRESOLVED_MEASUREMENTS_AND_RUNTIME_LIMIT_REQUIRED',sourceUnavailability:'BOUNDED_RESIDUAL_ONLY_UNKNOWN_CRITICAL_BEHAVIOR_BLOCKS'};
plan.authorization={marketingAuthorized:false,launchAuthorized:false,explicitOwnerLaunchAuthorityState:'NOT_GRANTED'};
delete plan.planDigest; plan.planDigest=await sha256Hex(plan);
await save('docs/BINRAT_PONS_LAUNCH_PLAN_V1.json',plan);
const source=new URL('src/launchConfig/ponsPlan.ts',root);
await writeFile(source,(await readFile(source,'utf8')).replace(/PONS_LAUNCH_PLAN_DIGEST = '[a-f0-9]{64}'/,`PONS_LAUNCH_PLAN_DIGEST = '${plan.planDigest}'`));
const matrix=await load('docs/LAUNCH_GATE_MATRIX_PONS_V1.json');
const oldPlan=matrix.launchPlanDigest;
matrix.schemaVersion='binrat.launch-gate-matrix/0.3'; matrix.launchPlanDigest=plan.planDigest;
for (const id of REQUIRED_LAUNCH_GATE_IDS) {
  const g=matrix.gates[id];g.requiredAt=GATE_PHASES[id];g.blocksLaunchAuthorization=GATE_PHASES[id].includes('PRE-ARM');
  g.evidenceDigests=g.evidenceDigests.map((d:string)=>d === oldPlan ? plan.planDigest : d);
}
const holder=matrix.gates.rat_radar_free_value_and_holder_gate_smoke;
holder.liveEvidence.stakeSource='L2_COMPOSED_READ_ONLY_PRODUCTION_DISABLED';
holder.liveEvidence.workingRatStatus='PLANNED';holder.liveEvidence.stakingRequired=true;
holder.exactRemainingRequirement='POST-LAUNCH ONLY: separately authorize principal/wallet binding, threshold, capacity enforcement and entitlement activation. The launch itself must create and verify the Staking vault.';
matrix.gates.actual_token_address_and_launch_execution_receipt.exactRemainingRequirement='POST-BROADCAST/PRE-PUBLIC: verify actual token/curve/vault creation semantics, exact transaction, block/hash, economics, assets, allocation and manifest match. No future receipt is needed to arm.';
matrix.explicitOwnerLaunchAuthorityState='NOT_GRANTED';matrix.launchAuthorization='BLOCKED';
delete matrix.matrixDigest;matrix.matrixDigest=await sha256Hex(matrix);
await save('docs/LAUNCH_GATE_MATRIX_PONS_V1.json',matrix);
const capability=await load('docs/CAPABILITY_MANIFEST_V0.json');
capability.currentLaunchPlan.planDigest=plan.planDigest;
capability.currentPonsLaunchConfiguration.stakingRequired=true;
capability.currentPonsLaunchConfiguration.workingRatStatus='PLANNED';
capability.currentPonsLaunchConfiguration.productionEntitlementActive=false;
capability.launchGateStatus.matrixDigest=matrix.matrixDigest;
capability.launchGateStatus.blockingGateCount=REQUIRED_LAUNCH_GATE_IDS.filter(id=>matrix.gates[id].blocksLaunchAuthorization && matrix.gates[id].status !== 'SATISFIED').length;
capability.launchGateStatus.evaluationPhase='PRE-ARM';
capability.launchAuthorization.requiredEvidence=REQUIRED_LAUNCH_GATE_IDS.filter(id=>GATE_PHASES[id].includes('PRE-ARM'));
await save('docs/CAPABILITY_MANIFEST_V0.json',capability);
process.stdout.write(`${JSON.stringify({planDigest:plan.planDigest,matrixDigest:matrix.matrixDigest,blockingPreArmGates:capability.launchGateStatus.blockingGateCount,launchAuthorized:false})}\n`);
